[general]
chain = "dev"
log4rs_config = "stegos-log4rs.toml"

[storage]
database_path = "testing/node02/database"

[keychain]
password_file = "testing/node02/password.txt"
wallet_skey_file = "testing/node02/wallet.skey"
wallet_pkey_file = "testing/node02/wallet.pkey"
network_skey_file = "testing/node02/network.skey"
network_pkey_file = "testing/node02/network.pkey"

[network]
bind_ip = "127.0.0.1"
bind_port = 10056
advertise_local_ips = false
hashcash_nbits = 4
seed_nodes = [
    "/ip4/127.0.0.1/tcp/10055",
    "/ip4/127.0.0.1/tcp/10057",
    "/ip4/127.0.0.1/tcp/10058",
]
advertised_addresses = [
    "/ip4/127.0.0.1/tcp/10056",
]

[api]
bind_ip = "127.0.0.1"
bind_port = 3146