[general]
chain = "dev"
prometheus_endpoint = "127.0.0.1:9892"
api_endpoint = "127.0.0.1:3146"
data_dir = "testing/node02"
force_check = true

[network]
endpoint = "127.0.0.1:10056"
advertised_endpoint = "127.0.0.1:10056"
handshake_puzzle_difficulty = 100
seed_nodes = [
    "127.0.0.1:10055",
    "127.0.0.1:10057",
    "127.0.0.1:10058",
]