[network]
node_id = "node02"
bind_ip = "127.0.0.1"
bind_port = 10056
advertise_local_ips = false
private_key = "testing/node02/private-key.pk8"
public_key = "testing/node02/public-key.der"
broadcast_topic = "chat"
seed_nodes = [
    "/ip4/127.0.0.1/tcp/10055",
]
advertised_addresses = [
    "/ip4/127.0.0.1/tcp/10056",
]
