stages:
  - fast_checks
  - build
  - test
  - code_coverage
  - release

before_script:
  - ci-scripts/install-deps.sh

# Running fast-checks to notice an author that his pull-request fails our standatds.
# This checks should not produce any artifacts
# Allow to fail until fix for RUSTSEC-2019-0003 is released
fast_checks:
  stage: fast_checks
  before_script: []
  script:
    - rustup component add rustfmt
    - cargo install cargo-audit
    - cargo audit
    - cargo fmt --all -- --check
  tags:
    - linux
  image: rust:1.34
  allow_failure: true

.build:
  stage: build
  script:
    - cargo build

build:linux:
  extends: .build
  image: rust:1.34
  tags:
    - linux

build:macos:
  extends: .build
  tags:
    - macos

.test:
  stage: test
  script:
    - cargo test --all -- --nocapture
  dependencies: []
  artifacts:
    expire_in: 1 week
    paths:
      - target/

test:linux:
  extends: .test
  image: rust:1.34
  tags:
    - linux

test:macos:
  extends: .test
  tags:
    - macos

code_coverage:
  stage: code_coverage
  image: rust:1.34
  before_script: []
  script:
    - ci-scripts/coverage.sh
  dependencies:
    - test:linux
  tags:
    - linux
  only:
    - dev
    - master

.release:
  stage: release
  when: manual
  dependencies: []
  artifacts:
    expire_in: 1 week
    paths:
      - release/

release:linux:
  extends: .release
  image: rust:1.34
  script:
    - cargo install --path . --root /usr/local && strip /usr/local/bin/stegos
    - mkdir -p release/linux && mv /usr/local/bin/stegos release/linux
  tags:
    - linux

release:macos:
  extends: .release
  script:
    - sudo cargo install --path . --root /usr/local && sudo strip /usr/local/bin/stegos
    - mkdir -p release/macos && mv /usr/local/bin/stegos release/macos
  tags:
    - macos

release:linux:static:
  extends: .release
  image: stegos/rust-musl-builder:1.34
  before_script: []
  script:
    - cargo install --path . --root /usr/local && strip /usr/local/bin/stegos
    - mkdir -p release/linux && mv /usr/local/bin/stegos release/linux/stegos-static
    - ldd release/linux/stegos-static >/tmp/out 2>&1 || true
    - grep "Not a valid dynamic program" /tmp/out
    - release/linux/stegos-static --version 
  tags:
    - linux

