[package]
name = "stegos"
version = "0.1.0"
authors = ["Stegos AG <info@stegos.cc>"]

[[bin]]
name = "stegos"
path = "src/stegos.rs"

[[bin]]
name = "crypto"
path = "examples/bulletproofs.rs"

[workspace]
members = [
    "api",
    "blockchain",
    "config",
    "consensus",
    "crypto",
    "keychain",
    "network",
    "runtime",
    "storage",
    "txpool"
]

[dependencies]
stegos_api = { path = "./api" }
stegos_blockchain = { path = "./blockchain" }
stegos_config = { path = "./config" }
stegos_consensus = { path = "./consensus" }
stegos_crypto = { path = "./crypto" }
stegos_keychain = { path = "./keychain" }
stegos_network = { path = "./network" }
stegos_runtime = { path = "./runtime" }
stegos_storage = { path = "./storage" }
stegos_txpool = { path = "./txpool" }

bytes = "0.4.10"
clap = "~2.32"
dirs = "~1.0"
futures = "0.1.25"
hex = "0.3.2"
lazy_static = "1.1.0"
slog = "~2.4"
rand = "0.5.5"
slog-async = "~2.3"
slog-term = "~2.4"
tokio-codec = "0.1.1"
tokio-io = "0.1.9"
tokio-stdin = "0.1.1"
tokio-current-thread = "0.1.3"
tokio = "0.1.11"

rust-libpbc = { git = "https://github.com/stegos/rust-pbcintf.git" }
libp2p = { git = "https://github.com/libp2p/rust-libp2p.git", rev = "e179951c74cb0c8916d27329f2dfd78917dddfb2" }

[[example]]
name = "bulletproofs"

[[example]]
name = "pbc"

[[example]]
name = "curve1174"

[[example]]
name = "floodsub"

[[example]]
name = "echo-server"

[dev-dependencies]
env_logger = "0.5.13"
lazy_static = "1.1.0"

[build-dependencies]


[profile.release]
opt-level = 3
