[package]
name = "stegos"
version = "0.1.0"
authors = ["Stegos AG <info@stegos.cc>"]

[[bin]]
name = "stegos"
path = "src/stegos.rs"

[workspace]
members = [
    "api",
    "blockchain",
    "config",
    "consensus",
    "crypto",
    "keychain",
    "network",
    "runtime",
    "storage",
    "txpool"
]

[dependencies]
stegos_api = { path = "./api" }
stegos_blockchain = { path = "./blockchain" }
stegos_config = { path = "./config" }
stegos_consensus = { path = "./consensus" }
stegos_crypto = { path = "./crypto" }
stegos_keychain = { path = "./keychain" }
stegos_network = { path = "./network" }
stegos_runtime = { path = "./runtime" }
stegos_storage = { path = "./storage" }
stegos_txpool = { path = "./txpool" }

clap = "~2.32"
dirs = "~1.0"
slog = "~2.4"
slog-async = "~2.3"
slog-term = "~2.4"

[build-dependencies]
