[package]
name = "stegos"
version = "0.1.0"
authors = ["Stegos AG <info@stegos.cc>"]
edition = "2018"
build = "build.rs"

[[bin]]
name = "stegos"
path = "src/stegos.rs"

[workspace]
members = [
    "blockchain",
    "config",
    "consensus",
    "crypto",
    "keychain",
    "network",
    "node",
    "txpool",
    "serialization"
]

[dependencies]
stegos_blockchain = { path = "./blockchain" }
stegos_config = { path = "./config" }
stegos_consensus = { path = "./consensus" }
stegos_crypto = { path = "./crypto" }
stegos_keychain = { path = "./keychain" }
stegos_network = { path = "./network" }
stegos_node = { path = "./node" }
stegos_txpool = { path = "./txpool" }
stegos_wallet = { path = "./wallet" }
stegos_serialization = { path = "./serialization" }

clap = "2.32"
dirs = "1.0"
futures = "0.1"
tokio-io = "0.1"
tokio-timer = "0.2"
tokio = "0.1"
log = "0.4"
log4rs = { version = "0.8", features = ["all_components", "gzip", "file", "toml_format"]}
failure = "0.1"
rustyline = "2.1"
lazy_static = "1.1"
atty = "0.2"
regex = "1.0"

[dev-dependencies]
simple_logger = "1.0"

[build-dependencies]
vergen = "3.0.4"

[profile.dev]
opt-level = 2
debug = true
debug-assertions = true
