[general]
chain = "dev"
prometheus_endpoint = "127.0.0.1:9891"
api_endpoint = "127.0.0.1:3145"
data_dir = "dev/node01"
consistency_check = "full"

[network]
endpoint = "127.0.0.1:10055"
advertised_endpoint = "127.0.0.1:10055"
handshake_puzzle_difficulty = 100
readiness_threshold = 0
seed_nodes = [
    "127.0.0.1:10056",
    "127.0.0.1:10057",
    "127.0.0.1:10058",
    "127.0.0.1:10059",
    "127.0.0.1:10060",
    "127.0.0.1:10061",
]