[package]
name = "stegos_node"
version = "0.1.0"
authors = ["Stegos AG <info@stegos.cc>"]
build = "build.rs"

[dependencies]
stegos_config = { path = "../config" }
stegos_crypto = { path = "../crypto" }
stegos_blockchain = { path = "../blockchain" }
stegos_network = { path = "../network" }
stegos_keychain = { path = "../keychain" }
log = "0.4"
failure = "0.1.2"
failure_derive = "0.1.2"
futures = "0.1.25"
tokio-timer = "0.2"
chrono = "0.4"
protobuf = "2.2"
serde = "1.0"
serde_derive = "1.0"
rand = "0.6"
simple_logger = "1.0"
clap = "2.32"

[build-dependencies]
protobuf-codegen-pure = "2.2"

[[bin]]
name = "bootstrap"
path = "src/bootstrap.rs"