[package]
name = "stegos_blockchain"
version = "0.1.0"
authors = ["Stegos AG <info@stegos.cc>"]

[dependencies]
stegos_keychain = { path = "../keychain" }
stegos_crypto = { path = "../crypto" }
chrono = "0.4"
rand = "0.6"
log = "0.4"
failure = "0.1"
failure_derive = "0.1"

[dev-dependencies]
simple_logger = "1.0"
