[package]
name = "stegos_consensus"
version = "0.1.0"
authors = ["Stegos AG <info@stegos.cc>"]
edition = "2018"

[dependencies]
log = "0.4"
failure = "0.1"
stegos_crypto = { path = "../crypto" }
bitvector = "0.1"

[dev-dependencies]
stegos_keychain = { path = "../keychain" }
simple_logger = "1.0"