[general]
chain = "dev"
log4rs_config = "stegos-log4rs.toml"
prometheus_endpoint = "127.0.0.1:9893"

[storage]
database_path = "testing/node03/database"

[keychain]
password_file = "testing/node03/password.txt"
wallet_skey_file = "testing/node03/wallet.skey"
wallet_pkey_file = "testing/node03/wallet.pkey"
network_skey_file = "testing/node03/network.skey"
network_pkey_file = "testing/node03/network.pkey"

[network]
bind_ip = "127.0.0.1"
bind_port = 10057
advertise_local_ips = false
hashcash_nbits = 4
seed_nodes = [
    "/ip4/127.0.0.1/tcp/10055",
    "/ip4/127.0.0.1/tcp/10056",
    "/ip4/127.0.0.1/tcp/10058",
]
advertised_addresses = [
    "/ip4/127.0.0.1/tcp/10057",
]

[api]
bind_ip = "127.0.0.1"
bind_port = 3147