[general]
chain = "dev"
log4rs_config = "stegos-log4rs.toml"

[storage]
database_path = "testing/node03/database"

[keychain]
private_key = "testing/node03/stegos.skey"
public_key = "testing/node03/stegos.pkey"

[network]
bind_ip = "127.0.0.1"
bind_port = 10057
advertise_local_ips = false
seed_nodes = [
    "/ip4/127.0.0.1/tcp/10055",
    "/ip4/127.0.0.1/tcp/10056",
    "/ip4/127.0.0.1/tcp/10058",
]
advertised_addresses = [
    "/ip4/127.0.0.1/tcp/10057",
]

[api]
bind_ip = "127.0.0.1"
bind_port = 3147